### ISSUE TITLE
TypeError: The supplied argument maps to TFF type.. which is incompatible with the requested type

### ISSUE THREAD

**Issue by Ndiaye01** [google-research/federated#16]
Hello;
While running the script emnist_with_targeted_attack , I ran into the following error:

....
....
....
Building Iterative Process!
Traceback (most recent call last):
  File "emnist_with_targeted_attack.py", line 327, in <module>
    app.run(main)
  File "C:\Users\ngndiaye\AppData\Roaming\Python\Python37\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "C:\Users\ngndiaye\AppData\Roaming\Python\Python37\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "emnist_with_targeted_attack.py", line 272, in main
    server_optimizer_fn=server_optimizer_fn)
  File "C:\Users\ngndiaye\federated\targeted_attack\attacked_fedavg.py", line 470, in build_federated_averaging_process_attacked
    federated_dataset_type)
  File "C:\Users\ngndiaye\federated\targeted_attack\attacked_fedavg.py", line 375, in build_run_one_round_fn_attacked
    federated_bool_type)
  File "C:\Users\ngndiaye\AppData\Roaming\Python\Python37\site-packages\tensorflow_federated\python\core\impl\wrappers\computation_wrapper.py", line 407, in __call__
    result = fn_to_wrap(*args, **kwargs)
  File "C:\Users\ngndiaye\federated\targeted_attack\attacked_fedavg.py", line 403, in run_one_round
    weight=weight_denom)
  File "C:\Users\ngndiaye\AppData\Roaming\Python\Python37\site-packages\tensorflow_federated\python\core\impl\utils\function_utils.py", line 520, in __call__
    arg = pack_args(self._type_signature.parameter, args, kwargs, context)
  File "C:\Users\ngndiaye\AppData\Roaming\Python\Python37\site-packages\tensorflow_federated\python\core\impl\utils\function_utils.py", line 316, in pack_args
    arg = pack_args_into_struct(args, kwargs, parameter_type, context)
  File "C:\Users\ngndiaye\AppData\Roaming\Python\Python37\site-packages\tensorflow_federated\python\core\impl\utils\function_utils.py", line 237, in pack_args_into_struct
    result_elements.append((name, context.ingest(arg_value, elem_type)))
  File "C:\Users\ngndiaye\AppData\Roaming\Python\Python37\site-packages\tensorflow_federated\python\core\impl\federated_context\federated_computation_context.py", line 101, in ingest
    val = value_impl.to_value(val, type_spec, self._context_stack)
 
**File"C:\Users\ngndiaye\AppData\Roaming\Python\Python37\sitepackages\tensorflow_federated\python\core\impl\value_impl.py", line 464, in to_value 'the requested type {}.'.format(result.type_signature, type_spec))**

**TypeError: The supplied argument maps to TFF type {<float32[3,3,1,32],float32[32],float32[3,3,32,64],float32[64],float32[9216,128],float32[128],float32[128,10],float32[10]>}@CLIENTS, which is incompatible with the requested type {<trainable=<float32[3,3,1,32],float32[32],float32[3,3,32,64],float32[64],float32[9216,128],float32[128],float32[128,10],float32[10]>,non_trainable=<>>}@CLIENTS.**

I used _Tensorflow VERSION 2.3.1_ , _Tensorflow Federated VERSION 0.17.0_ and _Keras VERSION 2.4.0_ and installed it via pip.
Could you specify which version of tf /keras to use with  tff ? Thanks a lot.

**Comment by kairouzp** [comment]
Did you make any changes to the script?

**Comment by Ndiaye01** [comment]
> Did you make any changes to the script?

Hello Sir,
No ,I didn't make any change.

**Comment by kairouzp** [comment]
The fix by Zach Charles should address this issue. Please let us know if you are still having trouble running the script. Thanks.

**Comment by Ndiaye01** [comment]
It works! Thank you very much.

> The fix by Zach Charles should address this issue. Please let us know if you are still having trouble running the script. Thanks.
