### ISSUE TITLE
Shakespeare optimization throws and error

### ISSUE THREAD

**Issue by amitport** [google-research/federated#35]
hello, when running the following on the latest version (with tff-nightly and tf-nightly)
```
python optimization/main/federated_trainer.py
--task=shakespeare
--clients_per_round=10
--client_datasets_random_seed=1
--client_epochs_per_round=1
--total_rounds=1200
--client_batch_size=4
--shakespeare_sequence_length=80
--client_optimizer=sgd
--client_learning_rate=1
--server_optimizer=sgd
--server_learning_rate=1
--server_sgd_momentum=0.0
--experiment_name=shakespeare_baseline
```

I'm really just running the baseline from the adaptive optimization paper, so I can't think of any reason why this should fail.

I'm getting the following error:
```
Traceback (most recent call last):
  File "/home/amitport/federated-learning-research/federated_learning_research/google_tff_research/optimization/main/federated_trainer.py", line 264, in <module>
    app.run(main)
  File "/home/amitport/.conda/envs/tff/lib/python3.8/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/amitport/.conda/envs/tff/lib/python3.8/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/amitport/federated-learning-research/federated_learning_research/google_tff_research/optimization/main/federated_trainer.py", line 227, in main
    runner_spec = federated_shakespeare.configure_training(
  File "/home/amitport/federated-learning-research/federated_learning_research/google_tff_research/optimization/shakespeare/federated_shakespeare.py", line 98, in configure_training
    iterative_process = task_spec.iterative_process_builder(tff_model_fn)
  File "/home/amitport/federated-learning-research/federated_learning_research/google_tff_research/optimization/main/federated_trainer.py", line 201, in iterative_process_builder
    return fed_avg_schedule.build_fed_avg_process(
  File "/home/amitport/federated-learning-research/federated_learning_research/google_tff_research/optimization/shared/fed_avg_schedule.py", line 269, in build_fed_avg_process
    dummy_model = model_fn()
  File "/home/amitport/federated-learning-research/federated_learning_research/google_tff_research/optimization/shakespeare/federated_shakespeare.py", line 93, in tff_model_fn
    keras_model=model_builder(),
  File "/home/amitport/federated-learning-research/federated_learning_research/google_tff_research/optimization/shakespeare/federated_shakespeare.py", line 33, in create_shakespeare_model
    return shakespeare_models.create_recurrent_model(
  File "/home/amitport/federated-learning-research/federated_learning_research/google_tff_research/utils/models/shakespeare_models.py", line 55, in create_recurrent_model
    model.add(lstm_layer_builder())
  File "/home/amitport/.conda/envs/tff/lib/python3.8/site-packages/tensorflow/python/training/tracking/base.py", line 536, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/home/amitport/.conda/envs/tff/lib/python3.8/site-packages/tensorflow/python/keras/engine/sequential.py", line 228, in add
    output_tensor = layer(self.outputs[0])
  File "/home/amitport/.conda/envs/tff/lib/python3.8/site-packages/tensorflow/python/keras/layers/recurrent.py", line 668, in __call__
    return super(RNN, self).__call__(inputs, **kwargs)
  File "/home/amitport/.conda/envs/tff/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 970, in __call__
    return self._functional_construction_call(inputs, args, kwargs,
  File "/home/amitport/.conda/envs/tff/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1108, in _functional_construction_call
    outputs = self._keras_tensor_symbolic_call(
  File "/home/amitport/.conda/envs/tff/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 841, in _keras_tensor_symbolic_call
    return self._infer_output_signature(inputs, args, kwargs, input_masks)
  File "/home/amitport/.conda/envs/tff/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 881, in _infer_output_signature
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/amitport/.conda/envs/tff/lib/python3.8/site-packages/tensorflow/python/keras/layers/recurrent_v2.py", line 1153, in call
    inputs, initial_state, _ = self._process_inputs(inputs, initial_state, None)
  File "/home/amitport/.conda/envs/tff/lib/python3.8/site-packages/tensorflow/python/keras/layers/recurrent.py", line 868, in _process_inputs
    initial_state = self.get_initial_state(inputs)
  File "/home/amitport/.conda/envs/tff/lib/python3.8/site-packages/tensorflow/python/keras/layers/recurrent.py", line 650, in get_initial_state
    init_state = get_initial_state_fn(
  File "/home/amitport/.conda/envs/tff/lib/python3.8/site-packages/tensorflow/python/keras/layers/recurrent.py", line 2516, in get_initial_state
    return list(_generate_zero_filled_state_for_cell(
  File "/home/amitport/.conda/envs/tff/lib/python3.8/site-packages/tensorflow/python/keras/layers/recurrent.py", line 2998, in _generate_zero_filled_state_for_cell
    return _generate_zero_filled_state(batch_size, cell.state_size, dtype)
  File "/home/amitport/.conda/envs/tff/lib/python3.8/site-packages/tensorflow/python/keras/layers/recurrent.py", line 3014, in _generate_zero_filled_state
    return nest.map_structure(create_zeros, state_size)
  File "/home/amitport/.conda/envs/tff/lib/python3.8/site-packages/tensorflow/python/util/nest.py", line 867, in map_structure
    structure[0], [func(*x) for x in entries],
  File "/home/amitport/.conda/envs/tff/lib/python3.8/site-packages/tensorflow/python/util/nest.py", line 867, in <listcomp>
    structure[0], [func(*x) for x in entries],
  File "/home/amitport/.conda/envs/tff/lib/python3.8/site-packages/tensorflow/python/keras/layers/recurrent.py", line 3011, in create_zeros
    return array_ops.zeros(init_state_size, dtype=dtype)
  File "/home/amitport/.conda/envs/tff/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "/home/amitport/.conda/envs/tff/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py", line 2911, in wrapped
    tensor = fun(*args, **kwargs)
  File "/home/amitport/.conda/envs/tff/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py", line 2960, in zeros
    output = _constant_if_small(zero, shape, dtype, name)
  File "/home/amitport/.conda/envs/tff/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py", line 2896, in _constant_if_small
    if np.prod(shape) < 1000:
  File "<__array_function__ internals>", line 5, in prod
  File "/home/amitport/.conda/envs/tff/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 3030, in prod
    return _wrapreduction(a, np.multiply, 'prod', axis, dtype, out,
  File "/home/amitport/.conda/envs/tff/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
  File "/home/amitport/.conda/envs/tff/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 871, in __array__
    raise NotImplementedError(
NotImplementedError: Cannot convert a symbolic Tensor (lstm/strided_slice:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported
```

Thank you

**Comment by zcharles8** [comment]
What version of python are you using? This looks like https://github.com/tensorflow/models/issues/9706 which seems to be resolved in multiple cases by using python 3.6.

**Comment by zcharles8** [comment]
Digging deeper, it might also be a `numpy` compatibility issue. Please let me know what versions of python and numpy led to this. It looks likely that downgrading one or both will resolve the issue.

**Comment by amitport** [comment]
Hi,

I just run this on an older setup with `python@3.7.10` `numpy@1.19.5` `tensorflow@2.4.1` `tensorflow-federated@0.18.0` and this repo at `hash=7384dc83bf3168df93eb832fc272f543d625594f`  (Dec 23, 2020)
and it works fine. (not sure where the exact problem is, but it is a regression)

My newer setup which fails is `python@3.8.8` `numpy@1.20.2` `tf-nightly@2.6.0.dev20210410` `tensorflow-federated-nightly@0.18.0.dev20210410` and this repo at `hash=3d532f5891a28931acebf35d4f1575238382ca75` (Apr 9, 2021)

**Comment by zcharles8** [comment]
@amitport Good to hear. Marking this as resolved, since it seems to be entirely within the scope of TF.
